# Generated by Django 5.2.8 on 2025-11-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_courierpartner'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='verified_purchase',
            field=models.BooleanField(default=True),
        ),
    ]
