from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    RegisterView,
    LoginView,
    ResetPasswordView,
    RequestOTPView,
    VerifyOTPView,
    ResetPasswordWithOTPView,
    CheckUsernameView,
    AdminUsersView,
    AdminUserDetailView,
    AdminDashboardStatsView,
    AdminOrdersView,
    AdminProductsView,
    AdminSalesChartView,
    AdminAllCategoriesView,
    AdminCategoriesView,
    AdminCategoryDetailView,
    AdminProductsDetailView,
    AdminCreateProductView,
    AdminOrderDetailView,
    AdminProductVariantsView,
    AdminCategoryAttributesView,
    AdminDeleteCategoryAttributeView,
    UserProfileView,
    UserAddressesView,
    UserAddressDetailView,
    SetDefaultAddressView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('request-otp/', RequestOTPView.as_view(), name='request_otp'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('reset-password-otp/', ResetPasswordWithOTPView.as_view(), name='reset_password_otp'),
    path('check-username/', CheckUsernameView.as_view(), name='check_username'),
    path('admin/users/', AdminUsersView.as_view(), name='admin_users'),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view(), name='admin_user_detail'),
    path('admin/dashboard/stats/', AdminDashboardStatsView.as_view(), name='admin_dashboard_stats'),
    path('admin/orders/', AdminOrdersView.as_view(), name='admin_orders'),
    path('admin/orders/<int:pk>/', AdminOrderDetailView.as_view(), name='admin_order_detail'),
    path('admin/products/', AdminProductsView.as_view(), name='admin_products'),
    path('admin/products/create/', AdminCreateProductView.as_view(), name='admin_create_product'),
    path('admin/products/<int:pk>/', AdminProductsDetailView.as_view(), name='admin_product_detail'),
    path('admin/products/<int:product_id>/variants/', AdminProductVariantsView.as_view(), name='admin_product_variants'),
    path('admin/categories/<int:category_id>/attributes/', AdminCategoryAttributesView.as_view(), name='admin_category_attributes'),
    path('admin/categories/<int:category_id>/attributes/<int:attribute_id>/delete/', AdminDeleteCategoryAttributeView.as_view(), name='admin_delete_category_attribute'),
    path('admin/categories/', AdminCategoriesView.as_view(), name='admin_categories'),
    path('admin/categories-all/', AdminAllCategoriesView.as_view(), name='admin_categories_all'),
    path('admin/categories/<int:pk>/', AdminCategoryDetailView.as_view(), name='admin_category_detail'),
    path('admin/sales-chart/', AdminSalesChartView.as_view(), name='admin_sales_chart'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # User Profile URLs
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('addresses/', UserAddressesView.as_view(), name='user_addresses'),
    path('addresses/<int:address_id>/', UserAddressDetailView.as_view(), name='user_address_detail'),
    path('addresses/<int:address_id>/set-default/', SetDefaultAddressView.as_view(), name='set_default_address'),
]



