# Generated by Django 5.2.8 on 2025-11-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
