# Generated by Django 4.2.7 on 2025-11-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tracking_url', models.URLField(blank=True, help_text='URL template for tracking (use {awb} as placeholder)', null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Partner',
                'verbose_name_plural': 'Courier Partners',
                'ordering': ['name'],
            },
        ),
    ]
